// ============================================
// ARTICLE REGISTRY — single source of truth
// Add an article here, it appears on the hub + gets its own page automatically
// ============================================

export type Block =
  | { type: "p"; text: string }
  | { type: "h2"; text: string }
  | { type: "h3"; text: string }
  | { type: "ul"; items: string[] }
  | { type: "ol"; items: string[] }
  | { type: "callout"; title: string; text: string }
  | { type: "table"; head: string[]; rows: string[][] };

export type ArticleCategory =
  | "Measuring"
  | "Storage & Freezing"
  | "Baking Science"
  | "Buying & Growing";

export const ARTICLE_CATEGORIES: ArticleCategory[] = [
  "Measuring",
  "Storage & Freezing",
  "Baking Science",
  "Buying & Growing",
];

export interface Article {
  slug: string;
  title: string;
  short: string;
  dek: string;
  category: ArticleCategory;
  published: string;   // ISO date
  updated?: string;    // ISO date
  readMinutes: number;
  body: Block[];
  relatedCalculator?: string;
  relatedRecipes?: string[];
}

// Inline links use [label](/path) inside any text field and are rendered
// as real React elements — never injected as raw HTML.
export const ARTICLES: Article[] = [
  {
    slug: "how-many-blueberries-in-a-cup",
    title: "How Many Blueberries Are in a Cup?",
    short: "How Many Blueberries in a Cup?",
    dek: "The short answer is about 100 — but the number moves a lot depending on what kind of berry you bought and whether it is frozen.",
    category: "Measuring",
    published: "2026-08-05",
    readMinutes: 5,
    relatedCalculator: "median-berry",
    relatedRecipes: ["blueberry-muffins", "classic-blueberry-pie"],
    body: [
      { type: "p", text: "A US cup of fresh cultivated blueberries holds roughly **100 berries** and weighs about **148 grams**, or 5.2 ounces. If you only needed one number, that is the one." },
      { type: "p", text: "But that figure hides a surprising amount of variation, and if you are scaling a recipe up or costing out a harvest, the variation is the part that matters." },
      { type: "h2", text: "Why it is not just volume divided by berry size" },
      { type: "p", text: "The intuitive approach is to divide the volume of a cup by the volume of one berry. A US cup is 236.6 mL and a median blueberry is about 1.07 cm³, which suggests roughly 221 berries per cup." },
      { type: "p", text: "That answer is wrong by more than double, because berries are spheres and spheres do not tile. Pour any quantity of equal spheres into a container and they settle into what physicists call random close packing, occupying about **64%** of the available space. The remaining 36% is air in the gaps." },
      { type: "p", text: "Apply that correction and you get roughly 151 mL of actual fruit in a cup, which lands at about 100 to 141 berries depending on berry size. Our [median berry converter](/median-berry) does this arithmetic for you." },
      { type: "callout", title: "The rule of thumb", text: "One cup of fresh cultivated blueberries is about 100 berries and 148 g. One pint is about 2 cups. One pound is about 3 cups, or roughly 300 berries." },
      { type: "h2", text: "Cultivated versus wild changes everything" },
      { type: "p", text: "Almost every published figure, including ours, assumes cultivated highbush blueberries — the large ones sold in plastic clamshells. Wild lowbush berries are dramatically smaller, commonly around 40% less volume per berry." },
      { type: "p", text: "That means a cup of wild blueberries can contain 200 or more individual berries at a similar total weight. If a recipe was written for wild berries and you use cultivated ones by count, you will add far too much fruit." },
      {
        type: "table",
        head: ["Measure", "Cultivated (approx.)", "Weight"],
        rows: [
          ["1 cup", "100 berries", "148 g / 5.2 oz"],
          ["1 pint", "200 berries", "296 g / 10.4 oz"],
          ["1 pound", "300 berries", "454 g / 16 oz"],
          ["1 quart", "400 berries", "592 g / 20.9 oz"],
        ],
      },
      { type: "h2", text: "Frozen berries measure differently" },
      { type: "p", text: "Water expands roughly 9% when it freezes, and a blueberry is about 84% water. Frozen berries are therefore slightly larger and, more importantly, they do not settle the same way — ice crystals on the surface make them cling instead of flowing into gaps." },
      { type: "p", text: "In practice a cup of frozen blueberries holds a few percent fewer berries than a cup of fresh. For baking this rarely matters. For anything where you are counting, measure frozen fruit by weight instead of volume." },
      { type: "h2", text: "How to measure accurately" },
      { type: "ol", items: [
        "Use a kitchen scale if you have one. Weight ignores packing entirely and is the only truly reliable method.",
        "If measuring by volume, spoon berries into the cup rather than scooping. Scooping compacts them and overfills by up to 10%.",
        "Do not level the top with a knife the way you would with flour. You will crush fruit and change the measure.",
        "For frozen berries, do not thaw before measuring. Thawed fruit collapses and packs far denser.",
      ]},
      { type: "h2", text: "Does the precision actually matter?" },
      { type: "p", text: "For most baking, no. A muffin batter tolerates a quarter cup either way without complaint. Where it does matter is in pie and preserves, because both depend on the ratio of fruit to thickener." },
      { type: "p", text: "Too much fruit in a pie and the filling floods when you cut it; too little and the crust caves. If you are sizing a pie, the [pie dish calculator](/pie-dish) works from your actual dish dimensions, and our [classic blueberry pie](/recipes/classic-blueberry-pie) lists both cups and berry counts." },
      { type: "p", text: "The full set of constants behind these figures, and their limitations, is documented on our [methodology page](/methodology)." },
    ],
  },

  {
    slug: "how-to-freeze-blueberries",
    title: "How to Freeze Blueberries the Right Way",
    short: "How to Freeze Blueberries",
    dek: "Do not wash them first. That single mistake is why most home-frozen blueberries end up as one solid purple brick.",
    category: "Storage & Freezing",
    published: "2026-08-05",
    readMinutes: 6,
    relatedRecipes: ["blueberry-jam", "blueberry-muffins"],
    body: [
      { type: "p", text: "Blueberries freeze better than almost any other fruit. They hold their shape, they keep for a year, and unlike strawberries they do not collapse into mush on thawing. The technique is simple, but there is one counterintuitive rule that determines whether it works." },
      { type: "callout", title: "The one rule", text: "Do not wash blueberries before freezing. Surface moisture turns to ice and cements the berries into a single mass. Rinse them after freezing, as you use them." },
      { type: "h2", text: "Why washing first ruins them" },
      { type: "p", text: "A fresh blueberry is coated in a natural waxy bloom — the dusty pale film on the skin. That bloom is a moisture barrier the plant produced to protect the fruit, and it is exactly what keeps individual berries from fusing in the freezer." },
      { type: "p", text: "Wash the bloom away and you leave a wet skin. Water on the surface freezes into bridges between adjacent berries, and within hours you have a solid block you have to chisel apart. The berries inside are fine, but you can no longer pour out a half cup." },
      { type: "h2", text: "The method" },
      { type: "ol", items: [
        "Sort, do not wash. Pick out stems, leaves, and any soft or split berries. One rotting berry will taint the batch.",
        "Dry them if they are already damp. Spread on a towel and pat gently. Damp fruit must be dried before it goes in.",
        "Freeze in a single layer. Spread the berries on a parchment-lined sheet pan so they are not touching, and freeze for 2 to 4 hours until firm.",
        "Transfer to bags. Move the frozen berries into freezer bags or airtight containers, pressing out as much air as you can.",
        "Label with the date. They keep well for 10 to 12 months, and you will not remember otherwise.",
      ]},
      { type: "p", text: "Step three is what commercial processors call IQF, or individually quick frozen. It is the entire reason store-bought frozen berries pour freely, and it takes about four minutes of actual work at home." },
      { type: "h2", text: "Can you skip the sheet pan?" },
      { type: "p", text: "You can, and the berries will still be perfectly edible — they will simply be clumped. If you plan to use the whole bag at once for jam or a batch of syrup, dumping them straight into a bag is a reasonable shortcut. If you want to grab a handful for pancakes in February, spend the four minutes." },
      { type: "h2", text: "Using frozen blueberries" },
      { type: "p", text: "The universal rule for baking with frozen fruit is **do not thaw**. Thawed berries bleed, and the juice both streaks the batter grey-green and adds water the recipe did not budget for." },
      {
        type: "table",
        head: ["Use", "Thaw first?", "Adjustment"],
        rows: [
          ["Muffins, scones, pancakes", "No", "Toss frozen berries in flour; add 2-3 min bake time"],
          ["Pie and cobbler", "No", "Add 1 extra tbsp cornstarch; expect 10 min longer"],
          ["Jam and syrup", "No", "None — they break down anyway"],
          ["Smoothies", "No", "Frozen is better; replaces ice"],
          ["Topping yogurt or cereal", "Partially", "5 min at room temperature"],
        ],
      },
      { type: "p", text: "Our [muffin scaler](/muffin-scaler) and [jam yield calculator](/jam-yield) both work identically for fresh and frozen fruit, since they operate on weight." },
      { type: "h2", text: "How long do they actually last?" },
      { type: "p", text: "Frozen blueberries remain safe indefinitely at 0°F, but quality declines. Expect excellent results for 10 to 12 months, acceptable results through about 18 months, and a noticeable loss of texture and flavour after that." },
      { type: "p", text: "Freezer burn shows up as pale, dry, shrivelled patches. It is not dangerous, but those berries taste like cardboard. Pressing air out of the bag is the single best defence." },
      { type: "h2", text: "Does freezing destroy the nutrition?" },
      { type: "p", text: "No. Freezing preserves anthocyanins and vitamin C well — often better than a week of refrigeration, because the fruit is typically frozen at peak ripeness. Some studies find anthocyanins become marginally more available after freezing, as ice crystals rupture cell walls." },
      { type: "p", text: "You can compare figures for any quantity with the [nutrition calculator](/nutrition)." },
    ],
  },

  {
    slug: "why-blueberries-turn-green-in-baking",
    title: "Why Blueberries Turn Green in Muffins and Pancakes",
    short: "Why Blueberries Turn Green",
    dek: "Your batter is not spoiled. It is a pH reaction, it is harmless, and it is entirely preventable once you know the cause.",
    category: "Baking Science",
    published: "2026-08-05",
    readMinutes: 5,
    relatedRecipes: ["blueberry-muffins", "blueberry-pancakes"],
    body: [
      { type: "p", text: "You fold blueberries into a pale muffin batter, bake them, and pull out muffins shot through with streaks of grey-green. Nothing has gone wrong with your ingredients. You have run a chemistry experiment." },
      { type: "h2", text: "The pigment is a pH indicator" },
      { type: "p", text: "Blueberry colour comes from anthocyanins, a family of plant pigments that also colour red cabbage, blackberries, and purple sweet potatoes. Anthocyanins are natural pH indicators: they physically change molecular structure depending on the acidity around them." },
      { type: "p", text: "In acidic conditions they appear red to purple. Around neutral they shift toward violet-blue. In alkaline conditions they turn blue-green, then genuinely green." },
      { type: "p", text: "The interior of a muffin is a mildly alkaline environment, and where berry juice bleeds into batter, the pigment reports that alkalinity honestly by turning green." },
      { type: "callout", title: "It is completely safe", text: "Green blueberry streaks are a colour change in a plant pigment, not spoilage, mould, or a chemical contaminant. The taste is unaffected." },
      { type: "h2", text: "Baking soda is the usual culprit" },
      { type: "p", text: "Sodium bicarbonate is a base. It is in your batter to react with acid and produce carbon dioxide for lift, but any excess remains in the crumb and pushes pH up." },
      { type: "p", text: "This is why the problem is far more common in recipes that lean on baking soda than in those leaning on baking powder. Baking powder is a balanced product containing both a base and its own acid, so it disturbs pH much less." },
      { type: "p", text: "If your recipe calls for more than about a quarter teaspoon of baking soda per cup of flour and you are getting green streaks, the soda is almost certainly the cause." },
      { type: "h2", text: "Five ways to prevent it" },
      { type: "ol", items: [
        "Do not thaw frozen berries. Thawed fruit bleeds juice into the batter, and bleeding is what spreads pigment into contact with alkaline crumb.",
        "Toss berries in flour before folding. A thin flour coating is a physical barrier that slows juice migration.",
        "Fold minimally. Every extra stroke ruptures more berries. Six to eight folds is plenty.",
        "Add a little acid. A tablespoon of lemon juice, buttermilk instead of milk, or sour cream lowers pH enough to hold the colour.",
        "Drop berries onto pancakes in the pan rather than stirring them into the batter — the approach our [blueberry pancakes](/recipes/blueberry-pancakes) recipe uses for exactly this reason.",
      ]},
      { type: "h2", text: "Why store-bought muffins never do this" },
      { type: "p", text: "Commercial bakeries have the same chemistry problem and solve it with tools most home kitchens lack: buffered leavening systems that hold pH steady, berries coated in a sealing glaze, and in some cases added acidulants like citric acid specifically to protect colour." },
      { type: "p", text: "Some also use dried or infused berries, which contain far less free juice to bleed in the first place." },
      { type: "h2", text: "The same reaction, deliberately" },
      { type: "p", text: "You can demonstrate this in about a minute. Mash a few blueberries in two small bowls with a splash of water. Stir a pinch of baking soda into one and a squeeze of lemon juice into the other." },
      { type: "p", text: "The soda bowl shifts green within seconds. The lemon bowl turns bright reddish-purple. Same pigment, opposite ends of the pH scale — and a clear picture of what is happening inside your muffins." },
    ],
  },

  {
    slug: "how-to-store-fresh-blueberries",
    title: "How to Store Fresh Blueberries So They Last",
    short: "Storing Fresh Blueberries",
    dek: "Most blueberries spoil days early for one reason: they were stored in the container they were sold in.",
    category: "Storage & Freezing",
    published: "2026-08-05",
    readMinutes: 4,
    body: [
      { type: "p", text: "Handled properly, fresh blueberries keep for two to three weeks in the refrigerator. Handled the ordinary way — left in the clamshell on a middle shelf — they typically last five or six days before the first fuzzy one appears." },
      { type: "h2", text: "What actually spoils them" },
      { type: "p", text: "Three things, in order of importance: **moisture**, **ethylene and warmth**, and **one bad berry**." },
      { type: "p", text: "Surface moisture is the primary enemy. Mould spores are already present on the fruit and are harmless while the skin stays dry. Add water and they germinate. This is why washing before storage is such a costly mistake, and why condensation inside a sealed container is nearly as bad." },
      { type: "callout", title: "The core rule", text: "Store dry, unwashed, cold, and with airflow. Wash only the portion you are about to eat." },
      { type: "h2", text: "The method" },
      { type: "ol", items: [
        "Sort on arrival. Remove any soft, split, shrivelled, or mouldy berries. A single spoiling berry accelerates everything touching it.",
        "Do not wash. Leave the natural waxy bloom intact until you are ready to eat them.",
        "Get them out of the clamshell. Those containers trap humidity against the fruit at the bottom.",
        "Line a container with paper towel. Use a shallow container, add a paper towel, and store the berries no more than two or three deep.",
        "Leave the lid slightly open. Airflow lets moisture escape rather than condensing on the fruit.",
        "Refrigerate at the back. The back of a middle shelf is the most temperature-stable spot. Avoid the door.",
      ]},
      { type: "h2", text: "Should you use the vinegar rinse?" },
      { type: "p", text: "The popular vinegar soak — one part white vinegar to three parts water, a brief soak, then a thorough dry — does genuinely kill surface mould spores and can extend life noticeably." },
      { type: "p", text: "The catch is the drying step. Berries must be completely dry before they go back in the refrigerator, and if you rush it you have made things worse by removing the protective bloom while leaving moisture behind. Only worth doing if you will dry them properly on towels for an hour." },
      { type: "h2", text: "The crisper drawer question" },
      { type: "p", text: "Crisper drawers are designed to hold humidity, which is right for leafy greens and wrong for berries. If your drawer has a humidity slider, set it to low. Otherwise use an open shelf." },
      {
        type: "table",
        head: ["Storage method", "Expected life", "Notes"],
        rows: [
          ["Original clamshell, fridge", "5-7 days", "The default. Trapped humidity is the problem."],
          ["Lined container, lid ajar, fridge", "2-3 weeks", "Best fresh-storage method."],
          ["Countertop, room temperature", "1-2 days", "Only for berries eaten today."],
          ["Frozen (IQF method)", "10-12 months", "See [how to freeze blueberries](/articles/how-to-freeze-blueberries)."],
        ],
      },
      { type: "h2", text: "When to give up and freeze" },
      { type: "p", text: "The moment berries start looking dull, soft, or slightly wrinkled, stop trying to keep them fresh. They are still perfectly good for baking, and freezing them at that point captures what quality remains." },
      { type: "p", text: "Slightly past-prime berries are ideal for [small-batch jam](/recipes/blueberry-jam) or [compote](/recipes/blueberry-compote), where texture no longer matters and the concentrated sweetness of very ripe fruit is an advantage." },
    ],
  },

  {
    slug: "fresh-vs-frozen-blueberries-baking",
    title: "Fresh vs. Frozen Blueberries in Baking",
    short: "Fresh vs. Frozen for Baking",
    dek: "Frozen berries work in nearly every blueberry recipe. Here is what genuinely changes, and the two adjustments that matter.",
    category: "Baking Science",
    published: "2026-08-05",
    readMinutes: 5,
    relatedRecipes: ["blueberry-crisp", "blueberry-scones"],
    body: [
      { type: "p", text: "Frozen blueberries are cheaper, available year-round, and frequently picked riper than the fresh fruit next to them in the store. For most baking they are not a compromise. But they are not a drop-in substitute either, and two differences drive every adjustment you need to make." },
      { type: "h2", text: "Difference one: water" },
      { type: "p", text: "Freezing forms ice crystals inside the fruit that puncture cell walls. When the berry warms, those ruptured cells release juice that a fresh berry would have held. A frozen berry going into a hot oven sheds noticeably more liquid." },
      { type: "p", text: "In a pie or cobbler that extra liquid has to be absorbed by the thickener. In a muffin it becomes steam, which is why frozen-berry muffins often need a few extra minutes." },
      { type: "h2", text: "Difference two: structure" },
      { type: "p", text: "Those same ruptured cell walls make frozen berries softer once heated. They collapse more readily and are more likely to smear if you stir them into a batter. In a crisp or cobbler this is irrelevant. In a delicate scone it is the difference between distinct fruit and purple marbling." },
      { type: "callout", title: "The two universal adjustments", text: "1. Never thaw. Use frozen berries straight from the freezer. 2. Add one extra tablespoon of cornstarch to any pie, cobbler, or crisp filling." },
      { type: "h2", text: "Recipe by recipe" },
      {
        type: "table",
        head: ["Recipe type", "Frozen works?", "What to change"],
        rows: [
          ["Muffins and quick breads", "Yes", "Toss in flour, fold minimally, add 2-3 min"],
          ["Pancakes and waffles", "Yes", "Drop onto batter in the pan, not into the bowl"],
          ["Pie and cobbler", "Yes", "+1 tbsp cornstarch, +10 min bake"],
          ["Crisp and crumble", "Yes, excellent", "+1 tbsp cornstarch"],
          ["Scones", "Yes", "Use straight from freezer; work dough fast"],
          ["Jam, syrup, compote", "Yes, identical", "No change at all"],
          ["Fresh tart topping", "No", "Uncooked frozen berries weep and look dull"],
          ["Garnish", "No", "Use fresh"],
        ],
      },
      { type: "h2", text: "Why you must not thaw" },
      { type: "p", text: "Thawing is the single most common mistake. A thawed berry has already released its juice into a puddle at the bottom of the bowl, and that juice does three unhelpful things: it dyes the batter, it adds unmeasured liquid, and it reacts with alkaline leavening to produce [green streaks](/articles/why-blueberries-turn-green-in-baking)." },
      { type: "p", text: "Frozen berries folded in solid stay intact long enough for the surrounding batter to set around them." },
      { type: "h2", text: "The flour trick, and why it works" },
      { type: "p", text: "Tossing berries in a tablespoon of flour taken from the recipe's measured amount does two jobs at once. The coating absorbs surface juice as the berry warms, and it adds enough friction against the batter to slow the berry sinking to the bottom during baking." },
      { type: "p", text: "It is not a myth, but it is not magic either. It reduces sinking; it does not eliminate it. A thick batter matters more." },
      { type: "h2", text: "Cost and nutrition" },
      { type: "p", text: "Frozen fruit is typically cheaper per pound and dramatically cheaper out of season. Because it is picked and frozen at peak ripeness rather than shipped underripe, the nutritional profile often matches or exceeds supermarket fresh fruit." },
      { type: "p", text: "You can compare real prices per berry with the [cost calculator](/cost)." },
      { type: "h2", text: "The one place fresh genuinely wins" },
      { type: "p", text: "Anywhere the berry is not cooked. On top of a [lemon blueberry tart](/recipes/lemon-blueberry-tart), scattered over yogurt, or as a garnish, fresh fruit has a firmness and gloss that thawed fruit simply cannot reproduce." },
    ],
  },

  {
    slug: "how-many-blueberries-does-a-bush-produce",
    title: "How Many Blueberries Does One Bush Produce?",
    short: "Yield Per Bush",
    dek: "A mature highbush plant gives 5 to 10 pounds a season — but it takes six years to get there, and most first-time growers give up in year two.",
    category: "Buying & Growing",
    published: "2026-08-05",
    readMinutes: 5,
    relatedCalculator: "bush-yield",
    body: [
      { type: "p", text: "A healthy mature highbush blueberry produces **5 to 10 pounds** of fruit per season — somewhere between 1,500 and 3,000 individual berries. Exceptional plants in ideal conditions reach 15 pounds or more." },
      { type: "p", text: "The number that surprises people is how long it takes to get there." },
      { type: "h2", text: "Yield by plant age" },
      {
        type: "table",
        head: ["Age", "Typical yield", "Approx. berries"],
        rows: [
          ["Year 1-2", "0 (remove flowers)", "0"],
          ["Year 3", "1-2 lb", "300-600"],
          ["Year 4", "2-4 lb", "600-1,200"],
          ["Year 5", "4-7 lb", "1,200-2,100"],
          ["Year 6+", "5-10 lb", "1,500-3,000"],
          ["Year 8-15 (peak)", "8-15 lb", "2,400-4,500"],
        ],
      },
      { type: "p", text: "Our [bush yield calculator](/bush-yield) estimates totals for a given number of plants and ages." },
      { type: "h2", text: "Why you should remove the first years' flowers" },
      { type: "p", text: "It feels perverse, but pinching off every blossom in years one and two is the single highest-return thing a new grower can do. A young plant that is allowed to fruit spends its limited energy on berries instead of roots and canes." },
      { type: "p", text: "Sacrifice two seasons of a handful of fruit and you get a substantially larger plant that produces more, sooner, for decades. A well-managed highbush blueberry stays productive for 40 to 50 years." },
      { type: "h2", text: "What limits yield" },
      { type: "ul", items: [
        "**Soil pH.** This is the big one. Blueberries need acidic soil, pH 4.5 to 5.5. Above about 6.0 they cannot take up iron, leaves yellow, and yield collapses. Most garden soil is too alkaline without amendment.",
        "**Pollination.** Blueberries are partially self-fertile but yield far better with a second compatible variety nearby. Two different cultivars can increase production by 30% or more.",
        "**Water.** Shallow roots and no tolerance for drought or standing water. Consistent moisture during fruit development is critical.",
        "**Sun.** Six or more hours of direct sun. Shaded plants survive and barely fruit.",
        "**Pruning.** Old canes stop producing. Removing the oldest wood each winter keeps the plant renewing itself.",
        "**Birds.** An unnetted bush in a bird-heavy area can lose most of its crop in days.",
      ]},
      { type: "h2", text: "Highbush, lowbush, and rabbiteye" },
      { type: "p", text: "**Northern highbush** is the standard garden and commercial plant, and every figure above refers to it. **Rabbiteye** varieties suit hot southern climates and can exceed highbush yields at maturity, though they take longer to establish. **Lowbush** — the wild type — spreads as a low mat and yields far less per plant, but the berries are smaller, more intensely flavoured, and more numerous per pound." },
      { type: "h2", text: "How many plants do you need?" },
      { type: "p", text: "For fresh eating, two mature plants per person is a reasonable rule. A household that also wants to freeze fruit and make preserves should plan on four to six mature plants." },
      { type: "p", text: "At 5 to 10 pounds each, six mature bushes yield 30 to 60 pounds a season — roughly 90 to 180 cups. That is well beyond fresh eating, so plan for [freezing](/articles/how-to-freeze-blueberries) and [jam](/recipes/blueberry-jam) before the harvest arrives rather than during it." },
      { type: "callout", title: "A note on our numbers", text: "These are typical ranges from horticultural guidance, not a prediction for your garden. Climate, cultivar, soil, and management swing results enormously. Your regional agricultural extension service will have figures specific to where you live." },
    ],
  },

  {
    slug: "blueberry-nutrition-facts",
    title: "Blueberry Nutrition Facts, Per Cup and Per Berry",
    short: "Blueberry Nutrition",
    dek: "A cup of blueberries is 84 calories and 3.6 g of fiber. Here is the full breakdown, and an honest look at the health claims.",
    category: "Measuring",
    published: "2026-08-07",
    readMinutes: 6,
    relatedCalculator: "nutrition",
    body: [
      { type: "p", text: "One US cup of raw blueberries — about 148 g, or roughly 100 berries — contains **84 calories**. That is the number most people are looking for, and by the standards of sweet food it is a low one." },
      { type: "h2", text: "Full breakdown per cup" },
      {
        type: "table",
        head: ["Nutrient", "Per cup (148 g)", "Per berry (1.5 g)"],
        rows: [
          ["Calories", "84 kcal", "0.86 kcal"],
          ["Carbohydrates", "21.4 g", "0.22 g"],
          ["Fiber", "3.6 g", "0.04 g"],
          ["Sugars", "14.7 g", "0.15 g"],
          ["Protein", "1.1 g", "0.01 g"],
          ["Fat", "0.5 g", "trace"],
          ["Vitamin C", "14.4 mg", "0.15 mg"],
          ["Vitamin K", "28.6 mcg", "0.29 mcg"],
          ["Manganese", "0.5 mg", "trace"],
          ["Water", "~84%", "~84%"],
        ],
      },
      { type: "p", text: "Figures are for raw cultivated blueberries from USDA reference data. Our [nutrition calculator](/nutrition) will scale these to any quantity — cups, grams, or an exact berry count." },
      { type: "h2", text: "The sugar question" },
      { type: "p", text: "Roughly 15 g of the 21 g of carbohydrate in a cup is sugar, which sounds like a lot until you compare it to the alternatives. A cup of blueberries has less sugar than a medium banana and dramatically less than a cup of grapes or a glass of juice." },
      { type: "p", text: "More importantly, that sugar arrives packaged with 3.6 g of fiber and a great deal of water. Both slow absorption, which is why whole fruit behaves very differently in the body than the equivalent sugar in liquid form. Blueberries sit low on the glycemic index — generally in the low 50s." },
      { type: "h2", text: "Anthocyanins, and what is actually established" },
      { type: "p", text: "The deep blue-purple colour comes from anthocyanins, the compounds behind most blueberry health coverage. They are genuinely interesting: they are potent antioxidants in laboratory conditions, and blueberries contain more of them than most commonly eaten fruits." },
      { type: "p", text: "Where the coverage tends to overreach is in the leap from that to specific health outcomes. The honest summary is that observational studies associate regular berry consumption with cardiovascular and cognitive benefits, and some small trials are encouraging, but the evidence is not strong enough to promise any individual a particular result." },
      { type: "callout", title: "Worth stating plainly", text: "Blueberries are a nutrient-dense, high-fiber, low-calorie fruit. That alone is a good reason to eat them. They are not a treatment for any medical condition, and we are not qualified to give medical advice — talk to a doctor or registered dietitian about your own diet." },
      { type: "h2", text: "Fresh, frozen, and dried compared" },
      {
        type: "table",
        head: ["Form", "Calories", "Notes"],
        rows: [
          ["Fresh, 1 cup", "84 kcal", "The baseline"],
          ["Frozen, 1 cup", "~79 kcal", "Nutritionally near-identical; often frozen at peak ripeness"],
          ["Dried, 1/4 cup", "~127 kcal", "Water removed, so sugar and calories concentrate sharply"],
          ["Juice, 1 cup", "~110 kcal", "Fiber largely removed; behaves much more like sugar water"],
        ],
      },
      { type: "p", text: "Dried blueberries surprise people. Removing the water concentrates everything, so a small handful carries the sugar of a much larger volume of fresh fruit — and many commercial dried berries are sweetened on top of that. They are excellent in [cookies](/recipes/blueberry-cookies) and [granola](/recipes/blueberry-granola); they are not a one-for-one swap for fresh." },
      { type: "h2", text: "Wild versus cultivated" },
      { type: "p", text: "Wild lowbush blueberries are smaller, which means more skin per unit of weight — and the skin is where most anthocyanins live. Wild berries typically test higher in anthocyanin content per gram, with broadly similar calories and macronutrients." },
      { type: "p", text: "If you have the choice and the price is comparable, wild berries are the more nutrient-dense option. If not, the difference is small enough that the fruit you will actually eat is the better fruit." },
      { type: "h2", text: "How much is a reasonable amount?" },
      { type: "p", text: "Most dietary guidance frames fruit in servings rather than specific fruits — around two servings a day, where a serving is roughly a cup. A cup of blueberries daily fits comfortably inside that, contributes about 14% of the daily fiber target, and costs 84 calories." },
      { type: "p", text: "For portioning by count rather than volume, see [how many blueberries are in a cup](/articles/how-many-blueberries-in-a-cup)." },
    ],
  },

  {
    slug: "how-to-tell-if-blueberries-are-bad",
    title: "How to Tell If Blueberries Have Gone Bad",
    short: "Are They Still Good?",
    dek: "Wrinkled is fine. Soft is borderline. Mould means the container is done — and here is why the white dust is not mould.",
    category: "Storage & Freezing",
    published: "2026-08-07",
    readMinutes: 4,
    body: [
      { type: "p", text: "Blueberries decline gradually rather than failing all at once, which makes the call harder than it is with most fruit. Here is how to read them." },
      { type: "h2", text: "Throw them out" },
      { type: "ul", items: [
        "**Visible mould.** Fuzzy white, grey, or green growth. Discard the mouldy berries and anything touching them.",
        "**Leaking or mushy.** A berry that collapses and weeps when touched is done.",
        "**Sour, fermented, or alcoholic smell.** Fresh blueberries barely smell at all. Any pronounced sour or boozy note means fermentation.",
        "**Slimy film.** A slick coating on the fruit or in the container is bacterial.",
      ]},
      { type: "h2", text: "Still perfectly fine" },
      { type: "ul", items: [
        "**A dusty white coating.** This is the bloom — a natural wax the plant produces. It is a sign of freshness and minimal handling, not spoilage.",
        "**Wrinkled skin.** Purely moisture loss. The berry is past peak for eating raw but ideal for baking or jam.",
        "**Reddish or pink tinge.** An underripe berry. Tart, not spoiled.",
        "**A dry brown stem scar.** Normal.",
      ]},
      { type: "callout", title: "The bloom is not mould", text: "Bloom is a smooth, even, dusty film that rubs away under your thumb. Mould is fuzzy, raised, and localised in patches. If you can wipe it clean and the skin beneath is glossy, it is bloom." },
      { type: "h2", text: "Does one mouldy berry ruin the box?" },
      { type: "p", text: "Not the whole box, but do not ignore it. Mould spreads by direct contact and by spores. Remove the affected berry and its immediate neighbours, then use the rest quickly rather than putting them back in the refrigerator for another week." },
      { type: "p", text: "Do not wash the survivors and return them to storage — you would strip the bloom and add moisture, which is precisely what mould wants. See [how to store fresh blueberries](/articles/how-to-store-fresh-blueberries)." },
      { type: "h2", text: "Berries past their best are not wasted" },
      { type: "p", text: "Soft, wrinkled, slightly tired berries — with no mould, no smell, no slime — are better than fresh ones for anything cooked. They are sweeter, they break down faster, and texture no longer matters." },
      { type: "p", text: "Send them to [small-batch jam](/recipes/blueberry-jam), [compote](/recipes/blueberry-compote), or [syrup](/recipes/blueberry-syrup). Or freeze them immediately and deal with them later." },
      { type: "h2", text: "What about the fridge timeline?" },
      { type: "p", text: "As a rough guide: 5 to 7 days in the original clamshell, up to 2 to 3 weeks stored properly. Berries bought already soft were probably days old at the store and will not last either way." },
    ],
  },

  {
    slug: "blueberry-substitutes",
    title: "What to Substitute for Blueberries",
    short: "Blueberry Substitutes",
    dek: "Out of blueberries mid-recipe? Some swaps are one-for-one. Others need an adjustment, and a couple will not work at all.",
    category: "Baking Science",
    published: "2026-08-07",
    readMinutes: 5,
    body: [
      { type: "p", text: "The right substitute depends on what the blueberry is doing in the recipe. In a muffin it is a discrete pocket of soft fruit. In jam it is a source of pectin and acid. In a pie it is bulk plus liquid. Swap without accounting for the job and you get a soupy filling or a jam that never sets." },
      { type: "h2", text: "Direct one-for-one swaps" },
      {
        type: "table",
        head: ["Substitute", "Works in", "Adjustment"],
        rows: [
          ["Blackberries", "Nearly everything", "None; slightly more tart"],
          ["Raspberries", "Muffins, crisps, jam", "More fragile — fold even more gently"],
          ["Huckleberries", "Everything", "None; closest botanical relative"],
          ["Chopped strawberries", "Muffins, cobbler, crisp", "Wetter — add 1 tbsp cornstarch to fillings"],
          ["Cherries, pitted and halved", "Pies, cobblers, crisps", "Firmer; may need 5 extra minutes"],
          ["Cranberries, fresh", "Breads and muffins", "Very tart — increase sugar by 1/4 cup"],
        ],
      },
      { type: "h2", text: "Frozen for fresh" },
      { type: "p", text: "The easiest substitution of all is frozen blueberries for fresh, which works in every cooked application. Do not thaw, and add a tablespoon of cornstarch to any pie or cobbler filling. The full rundown is in [fresh vs. frozen blueberries in baking](/articles/fresh-vs-frozen-blueberries-baking)." },
      { type: "h2", text: "Dried blueberries" },
      { type: "p", text: "Dried berries are a substitute in cookies and scones, where extra moisture would be a problem, and a poor one in pies, where the fruit is supposed to supply juice." },
      { type: "p", text: "Use about **one-third the volume** of fresh, since dried fruit is concentrated. If the recipe has little liquid, plump them first in hot water or juice for 10 minutes and drain well. Our [blueberry cookies](/recipes/blueberry-cookies) are built around dried berries for exactly this reason." },
      { type: "callout", title: "The jam exception", text: "For jam and preserves, substitute carefully. Blueberries are moderately high in pectin and acid. Low-pectin fruit like strawberries or peaches will not set on lemon juice and time alone — you will need added pectin or a much longer reduction." },
      { type: "h2", text: "What does not work" },
      { type: "ul", items: [
        "**Blueberry pie filling from a can**, in place of fresh fruit. It is already thickened and sweetened; using it as a fresh-fruit substitute doubles both.",
        "**Blueberry jam**, in place of fresh berries in a batter. Far too much sugar, and it will not hold its shape.",
        "**Grapes.** Similar size and colour, entirely wrong texture and flavour when heated.",
        "**Blueberry-flavoured baking chips.** These are usually sugar, oil, and flavouring with no real fruit.",
      ]},
      { type: "h2", text: "Mixing fruit" },
      { type: "p", text: "You do not have to substitute all of it. Half blueberries and half something else works well in nearly every application, and mixed-berry versions of a crisp or cobbler are often better than single-fruit ones." },
      { type: "p", text: "Our [blueberry peach pie](/recipes/blueberry-peach-pie) is built on that principle — the peaches bring perfume and the blueberries bring structure and colour." },
    ],
  },

  {
    slug: "how-much-blueberries-for-a-pie",
    title: "How Many Blueberries Do You Need for a Pie?",
    short: "Blueberries Per Pie",
    dek: "A 9-inch double-crust pie takes about 6 cups — roughly 600 berries, or two pounds. Here is how that scales with dish size.",
    category: "Measuring",
    published: "2026-08-07",
    readMinutes: 5,
    relatedCalculator: "pie-dish",
    relatedRecipes: ["classic-blueberry-pie", "blueberry-crumb-pie", "blueberry-slab-pie"],
    body: [
      { type: "p", text: "A standard 9-inch double-crust blueberry pie needs **6 cups of blueberries** — about 2 pounds, 900 g, or roughly 600 individual berries. That is the answer for the most common case." },
      { type: "p", text: "Dish size changes it more than people expect, because a pie dish is closer to a cone than a cylinder and volume scales with the square of the radius." },
      { type: "h2", text: "By dish size" },
      {
        type: "table",
        head: ["Dish", "Blueberries", "Weight", "Approx. berries"],
        rows: [
          ["8-inch", "4.5 cups", "1.5 lb / 670 g", "~445"],
          ["9-inch standard", "6 cups", "2 lb / 900 g", "~594"],
          ["9-inch deep dish", "7.5 cups", "2.5 lb / 1.1 kg", "~740"],
          ["10-inch", "8 cups", "2.7 lb / 1.2 kg", "~790"],
          ["9x13 slab", "10 cups", "3.3 lb / 1.5 kg", "~990"],
        ],
      },
      { type: "p", text: "For a dish that is not on this list, the [pie dish calculator](/pie-dish) works from your actual diameter and depth." },
      { type: "h2", text: "Why you should mound the filling" },
      { type: "p", text: "Blueberries lose roughly 20% of their volume during baking as cells rupture and water escapes. A filling packed flush with the rim will bake down into a visible gap under the top crust." },
      { type: "p", text: "This is why nearly every good pie recipe tells you to mound the fruit slightly in the center. You are pre-compensating for shrinkage, not overfilling." },
      { type: "callout", title: "The thickener ratio", text: "The number that actually determines whether your pie sets is thickener per cup of fruit. For blueberries, use about 2 teaspoons of cornstarch per cup — so 1/4 cup of cornstarch for a 6-cup pie. Frozen berries need one extra tablespoon overall." },
      { type: "h2", text: "Buying quantities" },
      { type: "p", text: "Supermarket blueberries usually come in pint (about 2 cups) or 18-oz clamshells (about 3.5 cups). For a standard 9-inch pie you need **three pints** or **two 18-oz containers**." },
      { type: "p", text: "Buy slightly more than the recipe requires. Some berries will be soft or stemmed, and a pie is not a good place to discover you are a half cup short." },
      { type: "h2", text: "Crust style changes the number" },
      { type: "ul", items: [
        "**Double crust:** the baseline figures above.",
        "**Lattice top:** the same amount of fruit, but expect more evaporation through the gaps and a slightly firmer set.",
        "**Crumb top:** about 10% less fruit, since the topping takes up headroom. See [blueberry crumb pie](/recipes/blueberry-crumb-pie).",
        "**Open-faced or galette:** roughly half. A [galette](/recipes/blueberry-galette) uses about 3 cups.",
      ]},
      { type: "h2", text: "Cost" },
      { type: "p", text: "At typical supermarket prices, two pounds of fresh blueberries runs meaningfully more than the rest of the pie combined. Frozen fruit cuts that substantially and works well here — add the extra cornstarch and expect about 10 minutes more in the oven. The [cost per berry calculator](/cost) will price it out from whatever your store charges." },
    ],
  },

  {
    slug: "when-are-blueberries-in-season",
    title: "When Are Blueberries in Season?",
    short: "Blueberry Season",
    dek: "North American blueberry season runs April through September, rolling northward. Knowing the wave is how you buy them cheap.",
    category: "Buying & Growing",
    published: "2026-08-07",
    readMinutes: 4,
    body: [
      { type: "p", text: "In North America, blueberry season runs from roughly **April to September**, peaking in **July**. It is not one season but a wave that moves north as the year warms, which is why the fruit stays available for six months." },
      { type: "h2", text: "The rolling harvest" },
      {
        type: "table",
        head: ["Region", "Peak window"],
        rows: [
          ["Florida", "April - May"],
          ["Georgia and the Carolinas", "May - June"],
          ["California", "May - July"],
          ["New Jersey and the mid-Atlantic", "June - July"],
          ["Oregon and Washington", "July - September"],
          ["Michigan and the Midwest", "July - August"],
          ["Maine (wild lowbush)", "late July - early September"],
          ["British Columbia", "July - September"],
        ],
      },
      { type: "p", text: "Outside those months, most supermarket fruit is imported from Peru, Chile, Mexico, or Argentina, where the seasons are reversed. This is why blueberries never truly disappear — and also why winter berries cost more and often taste flatter, having been picked firm to survive the trip." },
      { type: "h2", text: "How to buy well" },
      { type: "ul", items: [
        "**Buy in July.** Peak supply means the lowest price and the shortest distance from field to shelf.",
        "**Look for the bloom.** That dusty white film means minimal handling. Glossy, heavily-handled berries have been rubbed.",
        "**Deep blue-purple, no red.** Blueberries do not ripen further after picking. A reddish berry will stay tart forever.",
        "**Check the bottom of the container.** Stains mean crushed fruit underneath.",
        "**Shake the clamshell gently.** Fresh berries move freely. Berries that stay put are sticking to each other, which means they are past it.",
      ]},
      { type: "callout", title: "Buy the glut, freeze the glut", text: "The single best move is to buy heavily at peak season, when prices are lowest and quality is highest, and freeze what you cannot eat. Properly frozen berries keep 10 to 12 months — long enough to bridge to the next season." },
      { type: "p", text: "The method matters: see [how to freeze blueberries the right way](/articles/how-to-freeze-blueberries). Freezing on a sheet pan first is what keeps them pourable instead of welded into a brick." },
      { type: "h2", text: "Wild season is shorter" },
      { type: "p", text: "Maine's wild lowbush harvest is a narrow window, usually a few weeks from late July. Fresh wild blueberries are hard to find outside the region and the season; almost all of the crop is frozen or processed immediately." },
      { type: "p", text: "If you see fresh wild berries, buy them. They are smaller, more intense, and better in baking than cultivated fruit — just remember there are far more of them per cup, as covered in [how many blueberries are in a cup](/articles/how-many-blueberries-in-a-cup)." },
      { type: "h2", text: "Picking your own" },
      { type: "p", text: "Pick-your-own farms open at local peak and charge a fraction of retail. Ripe berries fall into your hand with a light roll of the thumb — if you have to tug, it is not ready. A practised picker fills a 10-pound bucket in about an hour, which is roughly 30 cups, or enough for five pies." },
    ],
  },

  {
    slug: "why-blueberries-sink-in-muffins",
    title: "Why Blueberries Sink to the Bottom of Muffins",
    short: "Why Berries Sink",
    dek: "It is a density problem, not a mixing problem — and the flour trick everyone recommends only solves part of it.",
    category: "Baking Science",
    published: "2026-08-07",
    readMinutes: 4,
    relatedCalculator: "muffin-scaler",
    relatedRecipes: ["blueberry-muffins", "blueberry-coffee-cake"],
    body: [
      { type: "p", text: "You fold berries evenly through the batter, fill the tin, and bake. Twenty minutes later every blueberry is sitting in a purple layer at the bottom. The cause is straightforward physics, and the usual advice only addresses half of it." },
      { type: "h2", text: "The actual cause" },
      { type: "p", text: "A blueberry is denser than muffin batter. In a thin batter it simply sinks, and it keeps sinking for as long as the batter stays fluid." },
      { type: "p", text: "The critical window is the first several minutes in the oven, before the egg proteins and starches set. Batter also **thins as it warms** before it sets, so berries often sink faster in the oven than they did on the counter. Everything that prevents sinking works by shortening that window or by making the batter harder to move through." },
      { type: "h2", text: "What actually works, in order" },
      { type: "ol", items: [
        "**Use a thicker batter.** This is by far the most effective fix and the one people skip. A properly thick muffin batter should mound on a spoon, not pour. If yours ribbons off the spatula, it is too thin — hold back a little liquid.",
        "**Start hot.** Baking at 425°F for the first 5 minutes sets the exterior fast, closing the window. It also gives you the domed bakery top. Our [blueberry muffins](/recipes/blueberry-muffins) use exactly this.",
        "**Toss berries in flour.** Adds friction and absorbs surface moisture. It helps, but it is a partial fix, not a cure.",
        "**Use smaller berries.** Sink rate rises with size. Wild or small cultivated berries stay suspended far better than jumbo fruit.",
        "**Reserve some for the top.** Press a few berries into the surface after filling the tin. Purely cosmetic, and completely reliable.",
        "**Do not thaw frozen berries.** Frozen fruit is firmer, chills the surrounding batter, and moves less.",
      ]},
      { type: "callout", title: "The flour trick, honestly assessed", text: "Tossing berries in a tablespoon of flour is real but oversold. It reduces sinking; it does not stop it. If your batter is thin, floured berries will still end up at the bottom — just slightly more slowly." },
      { type: "h2", text: "Why bakery muffins do not have this problem" },
      { type: "p", text: "Commercial muffin batters are considerably thicker than most home recipes, often with more egg and less liquid, and they are baked in hot ovens with strong initial heat. Some operations also use berries coated in a starch or sugar glaze that adds surface grip." },
      { type: "p", text: "None of that is exotic. A thicker batter and a hot start gets you most of the way there in a home oven." },
      { type: "h2", text: "If it happens anyway" },
      { type: "p", text: "A muffin with the fruit at the bottom tastes exactly the same. It is a presentation problem, not a failure — and worth remembering before you rebuild a recipe that is otherwise working." },
      { type: "p", text: "For scaling a recipe up or down without changing the batter's consistency, the [muffin scaler](/muffin-scaler) keeps the ratios intact." },
    ],
  },
];

export function getArticleBySlug(slug: string) {
  return ARTICLES.find((a) => a.slug === slug);
}

export function getArticlesByCategory(cat: ArticleCategory) {
  return ARTICLES.filter((a) => a.category === cat);
}
